export const TICKER_CATEGORIES = {
  "미국 개별주식": [
    "TSLA","AAPL","NVDA","MSFT","AMZN","GOOGL","META","NFLX","AMD","AVGO",
    "MU","TSM","KO","BRK-B","ORCL","INTC","MRVL","PLTR","SNOW","COIN",
    "RKLB","IONQ","WDC","LLY","COST","V","QCOM","UBER","SPOT","SHOP",
    "ARM","AMAT","LRCX","ASML","BE","SMCI",
    "AAOI","CRWV","DDOG","GH","IREN","JPM","MSTR","NTRA","OKTA","SMR","UCTT",
  ],
  "미국 인덱스 ETF": ["VOO","SPY","IVV","QQQM","QQQ","VTI","DIA","IWM","VB","SCHG","VUG"],
  "반도체 ETF": ["SMH","SOXX"],
  "테크 섹터 ETF": ["XLK","VGT","IGV","HACK","WCLD","BOTZ"],
  "레버리지 ETF": [
    "TQQQ","SOXL","UPRO","QLD","SSO","SPXL","TECL","TSLL","NVDL","MSTU",
    "IONX","ORCX","USD","KORU","UGL","AGQ","UBT","TMF",
  ],
  "배당·인컴 ETF": ["SCHD","JEPI","JEPQ","SPYD","DGRO","QYLD","RYLD","VYM","DVY","VIG","HDV","SPHD","DIVO","PFF","XYLD","SDIV","QQQI","SPYM"],
  "배당주·리츠": ["O","MAIN","STAG","AGNC","JNJ","PG","PEP","MCD","ABBV","XOM","CVX","T","VZ","MO","MMM","IBM"],
  "GICS 11섹터 ETF": ["XLK","XLC","XLY","XLP","XLV","XLF","XLI","XLE","XLB","XLU","XLRE"],
  "테마 섹터 ETF": ["ITA","XBI","ICLN","LIT","ARKK","ARKF","ARKX","QTUM","VNQ","ARKG","PAVE"],
  "안전자산": ["GLD","SLV","TLT","SHY","USO","BND","AGG","HYG","IAU","GDX","IEF","SGOV","JEM"],
  "아시아 국가 ETF": ["INDA","EWJ","MCHI","EWT","VNM","EWY","EWH","EWS","EIDO","THD","FXI","EWM"],
  "유럽 국가 ETF": ["VGK","EWG","EWU","EWQ","EWI","EWL","EZU"],
  "기타 국가 ETF": ["EWZ","EWW","EEM","ACWI","EWA","KSA","VT","VXUS","IEFA","IEMG","VWO"],
  "국내 자산": ["KS11","KQ11","005930","000660","069500","360750"],
};

export const TICKER_LABELS = {
  // 한국 주식·ETF
  "KS11": "코스피",
  "KQ11": "코스닥",
  "005930": "삼성전자",
  "000660": "SK하이닉스",
  "069500": "KODEX 200",
  "360750": "TIGER 미국S&P500",

  // 미국 개별 주식
  "AAOI": "어플라이드 옵토",
  "AAPL": "애플",
  "AMD": "AMD",
  "AMAT": "어플라이드 머티리얼즈",
  "AMZN": "아마존",
  "ARM": "ARM 홀딩스",
  "ASML": "ASML",
  "AVGO": "브로드컴",
  "BE": "블룸 에너지",
  "BRK-B": "버크셔 B",
  "COIN": "코인베이스",
  "COST": "코스트코",
  "CRWV": "코어위브",
  "DDOG": "데이터독",
  "GH": "가던트 헬스",
  "GOOGL": "알파벳(구글)",
  "INTC": "인텔",
  "IONQ": "아이온큐",
  "IREN": "아이리스 에너지",
  "JPM": "JP모건",
  "KO": "코카콜라",
  "LLY": "일라이 릴리",
  "LRCX": "램 리서치",
  "META": "메타",
  "MRVL": "마벨 테크",
  "MSTR": "마이크로스트래티지",
  "MU": "마이크론",
  "NFLX": "넷플릭스",
  "NTRA": "나테라",
  "NVDA": "엔비디아",
  "OKTA": "옥타",
  "ORCL": "오라클",
  "PLTR": "팔란티어",
  "QCOM": "퀄컴",
  "RKLB": "로켓랩",
  "SHOP": "쇼피파이",
  "SMCI": "슈퍼마이크로",
  "SMR": "뉴스케일 파워",
  "SNOW": "스노우플레이크",
  "SPOT": "스포티파이",
  "TSM": "TSMC",
  "TSLA": "테슬라",
  "UBER": "우버",
  "UCTT": "울트라 클린",
  "V": "비자",
  "WDC": "웨스턴 디지털",
  "MSFT": "마이크로소프트",

  // 미국 지수 ETF
  "VOO": "S&P500 ETF",
  "SPY": "S&P500 ETF",
  "IVV": "S&P500 ETF",
  "DIA": "다우존스 ETF",
  "QQQ": "나스닥100 ETF",
  "QQQM": "나스닥100 ETF",
  "VTI": "미국 전체 ETF",
  "VT": "글로벌 전체 ETF",
  "ACWI": "글로벌 전체 ETF",
  "SCHG": "미국 성장주 ETF",
  "VUG": "미국 성장주 ETF",
  "IWM": "러셀2000 소형주 ETF",
  "VB": "미국 소형주 ETF",

  // 레버리지 ETF
  "TQQQ": "나스닥100 3배 ETF",
  "QLD": "나스닥100 2배 ETF",
  "SOXL": "반도체 3배 ETF",
  "UPRO": "S&P500 3배 ETF",
  "SPXL": "S&P500 3배 ETF",
  "SSO": "S&P500 2배 ETF",
  "TECL": "테크 3배 ETF",
  "TMF": "장기국채 3배 ETF",
  "UBT": "장기국채 2배 ETF",
  "UGL": "금 2배 ETF",
  "AGQ": "은 2배 ETF",
  "USD": "반도체 2배 ETF",
  "NVDL": "엔비디아 2배 ETF",
  "TSLL": "테슬라 2배 ETF",
  "MSTU": "마이크로스트래티지 2배 ETF",
  "ORCX": "오라클 1.5배 ETF",
  "IONX": "아이온큐 2배 ETF",
  "KORU": "한국주식 3배 ETF",
  "SPYM": "S&P500 YM ETF",

  // 반도체·테크 섹터 ETF
  "SMH": "반도체 ETF",
  "SOXX": "반도체 ETF",
  "XLK": "테크 섹터 ETF",
  "VGT": "테크 ETF",
  "IGV": "소프트웨어 ETF",
  "HACK": "사이버보안 ETF",
  "WCLD": "클라우드 ETF",
  "BOTZ": "로보틱스·AI ETF",
  "QTUM": "퀀텀컴퓨팅·AI ETF",
  "QQQI": "나스닥100 인컴 ETF",

  // 배당·인컴 ETF
  "SCHD": "배당 ETF",
  "JEPI": "JP모건 인컴 ETF",
  "JEPQ": "JP모건 나스닥 인컴 ETF",
  "SPYD": "고배당 ETF",
  "DGRO": "배당성장 ETF",
  "VIG": "배당성장 ETF",
  "VYM": "고배당 ETF",
  "DVY": "배당주 ETF",
  "QYLD": "나스닥 커버드콜 ETF",
  "RYLD": "러셀2000 커버드콜 ETF",
  "HDV": "iShares 고배당 ETF",
  "SPHD": "고배당 저변동 ETF",
  "DIVO": "배당 커버드콜 ETF",
  "PFF": "우선주 ETF",
  "XYLD": "S&P500 커버드콜 ETF",
  "SDIV": "글로벌 고배당 ETF",

  // 배당주·리츠
  "O": "리얼티인컴",
  "MAIN": "메인스트리트 캐피털",
  "STAG": "스태그 인더스트리얼",
  "AGNC": "AGNC 인베스트먼트",
  "JNJ": "존슨앤드존슨",
  "PG": "P&G",
  "PEP": "펩시코",
  "MCD": "맥도날드",
  "ABBV": "애브비",
  "XOM": "엑슨모빌",
  "CVX": "셰브론",
  "T": "AT&T",
  "VZ": "버라이즌",
  "MO": "알트리아",
  "MMM": "3M",
  "IBM": "IBM",

  // GICS 섹터 ETF
  "XLC": "커뮤니케이션 ETF",
  "XLY": "경기소비재 ETF",
  "XLP": "필수소비재 ETF",
  "XLV": "헬스케어 ETF",
  "XLF": "금융 ETF",
  "XLI": "산업재 ETF",
  "XLE": "에너지 ETF",
  "XLB": "소재 ETF",
  "XLU": "유틸리티 ETF",
  "XLRE": "리츠 ETF",
  "VNQ": "리츠 ETF",

  // 테마 ETF
  "ITA": "항공우주·방위 ETF",
  "XBI": "바이오텍 ETF",
  "ICLN": "청정에너지 ETF",
  "LIT": "리튬·배터리 ETF",
  "ARKK": "ARK 혁신 ETF",
  "ARKF": "ARK 핀테크 ETF",
  "ARKX": "ARK 우주탐사 ETF",
  "ARKG": "ARK 바이오 ETF",
  "PAVE": "미국 인프라 ETF",

  // 안전자산·채권 ETF
  "GLD": "금 ETF",
  "IAU": "금 ETF",
  "GDX": "금광기업 ETF",
  "SLV": "은 ETF",
  "TLT": "미국 장기국채 ETF",
  "IEF": "미국 중기국채 ETF",
  "SHY": "미국 단기국채 ETF",
  "SGOV": "미국 단기채 ETF",
  "BND": "미국 채권 ETF",
  "AGG": "미국 채권 ETF",
  "HYG": "하이일드 채권 ETF",
  "USO": "원유 ETF",

  // 국가 ETF
  "INDA": "인도 ETF",
  "EWJ": "일본 ETF",
  "MCHI": "중국 ETF",
  "FXI": "중국 대형주 ETF",
  "EWT": "대만 ETF",
  "VNM": "베트남 ETF",
  "EWY": "한국 ETF",
  "EWH": "홍콩 ETF",
  "EWS": "싱가포르 ETF",
  "EIDO": "인도네시아 ETF",
  "THD": "태국 ETF",
  "KSA": "사우디아라비아 ETF",
  "EWA": "호주 ETF",
  "EWM": "말레이시아 ETF",
  "VGK": "유럽 ETF",
  "EZU": "유로존 ETF",
  "EWG": "독일 ETF",
  "EWU": "영국 ETF",
  "EWQ": "프랑스 ETF",
  "EWI": "이탈리아 ETF",
  "EWL": "스위스 ETF",
  "EWZ": "브라질 ETF",
  "EWW": "멕시코 ETF",
  "EEM": "신흥시장 ETF",
  "VWO": "신흥시장 ETF",
  "IEMG": "신흥시장 ETF",
  "IEFA": "선진국(미국외) ETF",
  "VXUS": "미국외 전세계 ETF",
  "JEM": "신흥시장 채권 ETF",
};

export const ALL_TICKERS = Object.values(TICKER_CATEGORIES).flat();

// All tickers that have a CSV price file and can be used in simulation
// (fallback — runtime loads data/supportedTickers.json from GitHub raw)
export const SUPPORTED_TICKERS = new Set([
  "000660","005930","069500","360750",
  "AAOI","AAPL","ACWI","AGG","AGQ","AMAT","AMD","AMZN","ARKF","ARKG","ARKK","ARKX",
  "ARM","ASML","AVGO","BE","BND","BOTZ","BRK-B","COIN","COST","CRWV","DDOG","DGRO",
  "DIA","DVY","EEM","EIDO","EWA","EWG","EWH","EWI","EWJ","EWL","EWM","EWQ","EWS",
  "EWT","EWU","EWW","EWY","EWZ","EZU","FXI","GDX","GH","GLD","GOOGL",
  "HACK","HYG","IAU","ICLN","IEF","IEFA","IEMG","IGV","INDA","INTC","IONQ","IONX",
  "IREN","ITA","IVV","IWM","JEM","JEPI","JEPQ","JPM","KO","KORU","KQ11","KS11","KSA",
  "LIT","LLY","LRCX","MCHI","META","MRVL","MSFT","MSTR","MSTU","MU","NFLX","NTRA",
  "NVDA","NVDL","OKTA","ORCL","ORCX","PAVE","PLTR","QCOM","QLD","QQQ","QQQI","QQQM",
  "QTUM","QYLD","RKLB","RYLD","SCHD","SCHG","SGOV","SHOP","SHY","SLV","SMCI","SMH",
  "SMR","SNOW","SOXL","SOXX","SPOT","SPXL","SPY","SPYD","SPYM","SSO","TECL","THD",
  "TLT","TMF","TQQQ","TSLA","TSLL","TSM","UBER","UBT","UCTT","UGL","UPRO","USD","USO",
  "V","VB","VGK","VGT","VIG","VNM","VNQ","VOO","VT","VTI","VUG","VWO","VXUS","VYM",
  "WCLD","WDC","XBI","XLB","XLC","XLE","XLF","XLI","XLK","XLP","XLRE","XLU","XLV","XLY",
  // 배당 유니버스 (배당왕 준비로 추가)
  "HDV","SPHD","DIVO","PFF","XYLD","SDIV","O","MAIN","STAG","AGNC",
  "JNJ","PG","PEP","MCD","ABBV","XOM","CVX","T","VZ","MO","MMM","IBM",
]);

export function getTickerLabel(ticker) {
  return TICKER_LABELS[ticker] || ticker;
}

export const BASE_URL =
  "https://raw.githubusercontent.com/klevera-lgtm/stockjeokrib/main/data/prices/";

export const SUPPORTED_TICKERS_URL =
  "https://raw.githubusercontent.com/klevera-lgtm/stockjeokrib/main/data/supportedTickers.json";
